name: Deploy to Namecheap via FTP

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
      with:
        fetch-depth: 2
      
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.3
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        # 如果你的网站根目录不是默认的，修改下面的路径 (例如主域名通常是 public_html/，子域名通常是具体的文件夹名)
        server-dir: public_html/
